"""Offline native lookup data. Bounds cover the shipped timeline and native probes."""
import argparse
import math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def rows(name,kind,values):
    lines=[f'static const {kind} {name}[{len(values)}] = {{']
    for i in range(0,len(values),24): lines.append('    '+','.join(map(str,values[i:i+24]))+',')
    return '\n'.join(lines+['};'])

def content():
    masks=[]
    for b in range(6509):
        m1=int(math.pow(b,1.143))%20; m2=int(math.pow(b,1.2))%20
        masks.append(int(m1 not in (0,8,17,15)) | (int(m2 in (0,15))<<1) | (int(m2==8)<<2) | (int(m2==17)<<3))
    sea=[]
    for phase in range(4096):
        x=phase/5.0; wave=math.cos(.2*x)+math.sin(.3*x)*math.sin(.23*x)
        sea.append(max(0,min(7,math.floor((3-2*wave*math.sin(x))*7/9+.5))))
    return '// Generated by tools/export_math_tables.py; do not edit.\n'+ '\n'.join([
        rows('ocean_text_mask','uint8_t',masks),rows('ocean_height','uint8_t',sea),
        rows('access_limit','uint8_t',[max(1,32-int(math.pow(b,1.2))) for b in range(18)]),
        rows('wipe_count','uint16_t',[int(math.pow(b,1.4)) for b in range(61)]),
        rows('clear_count','uint16_t',[int(math.pow(b,2.2)) for b in range(33)]),
        rows('poweroff_height','uint8_t',[int(20/math.pow(b,1.3)) for b in range(1,11)])])+'\n'
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    target=ROOT/'src/math_tables.inc';text=content()
    if a.check: assert target.read_text()==text, 'math tables stale'
    else: target.write_text(text)
