"""Export only declarative corpus and scheduling conditions, never rendered frames.

Random corruption remains a runtime operation in C, in source evaluation order.
Word-list multiplication reuses the same initialized text (including trailing empty
line), as Python does. The authored C implementation owns all animation behavior.
"""
import argparse
import ast
from dataclasses import dataclass
import json
from pathlib import Path
import re
import sys
sys.dont_write_bytecode = True
ROOT=Path(__file__).resolve().parents[1]
REFERENCE_ROOT=ROOT/'archive/python'
sys.path.insert(0,str(REFERENCE_ROOT))
from animation_functions import work_out_date

@dataclass
class Template:
    raw: str
    repeat: int=1
    def __mul__(self,n): return Template(self.raw,self.repeat*n)

def literal(value): return json.dumps(value,ensure_ascii=True)
def number(node): return eval(compile(ast.Expression(node),'constant','eval'),{'__builtins__':{}})

def export():
    corruptions=[]
    def corrupt(text,chance,ignore=''):
        index=len(corruptions)
        corruptions.append((text,chance,ignore))
        return f'\x01{index}\x02'
    env={'split_word_template':Template,'fuck_up_text':corrupt,'work_out_date':work_out_date}
    module=ast.parse((REFERENCE_ROOT/'string_defs.py').read_text(encoding='utf-8'))
    exec(compile(ast.Module(body=[n for n in module.body if not isinstance(n,(ast.Import,ast.ImportFrom))],type_ignores=[]),'string_defs.py','exec'),env)
    header=['/* Generated by tools/export_data.py; source corpus, not replay output. */','#ifndef CREDITS_DATA_IDS_H','#define CREDITS_DATA_IDS_H','enum TextId {']
    source=['/* Generated by tools/export_data.py. */']
    totals=[]
    for key,value in env['data_strings'].items():
        header.append(f'    TEXT_{key.upper()},')
        raw=value.raw if isinstance(value,Template) else value
        segments=[]
        for piece in re.split('(\x01[0-9]+\x02)',raw):
            if piece.startswith('\x01'): segments.append(corruptions[int(piece[1:-1])])
            elif piece: segments.append((piece,0,''))
        source.append(f'static const DataSegment segments_{key}[] = {{')
        for text,chance,ignore in segments:
            source.append(f'    {{{literal(text)}, {chance}, {literal(ignore)}}},')
        source.append('};')
        full=''.join(s[0] for s in segments)
        totals.append((key,len(segments),int(isinstance(value,Template)),value.repeat if isinstance(value,Template) else 1,len(full)))
    source.append('static const TextDefinition text_definitions[TEXT_COUNT] = {')
    for key,count,word,repeat,length in totals: source.append(f'    {{"{key}", segments_{key}, {count}, {word}, {repeat}, {length}}},')
    source.append('};')
    header.extend(['    TEXT_COUNT','};','enum SceneId {'])
    tree=ast.parse((REFERENCE_ROOT/'animation_scenes.py').read_text(encoding='utf-8'))
    assignments={n.targets[0].id:n.value for n in tree.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name)}
    names=assignments['all_scenes'].elts
    defs=[]; conditions=[]; generator_count=0
    def cond(n):
        fn=n.func.attr; a=n.args
        if fn=='always': return '1'
        if fn=='combine_conditions': return '('+' && '.join(cond(x) for x in a)+')'
        v=number(a[0])
        if fn=='every_n_beats': return f'b % {v} == 0'
        if fn=='before_n': return f'b < {v}'
        if fn=='at_beat': return f'b == {v}'
        v2=number(a[1])
        if fn=='every_on_off': return f'b % {v+v2} < {v}'
        if fn=='every_off_on': return f'b % {v+v2} >= {v}'
        raise ValueError(ast.unparse(n))
    for name in names:
        scene=assignments[name.id]; key=ast.literal_eval(scene.args[0]); generators=scene.args[1].elts
        header.append(f'    SC_{key.upper()},')
        source.append(f'static const int starts_{key}[] = {{'+', '.join(str(number(g.args[0])) for g in generators)+'};')
        defs.append(f'    {{"{key}", {len(generators)}, starts_{key}}},')
        conditions.append(f'    case SC_{key.upper()}: switch (g) {{')
        for i,g in enumerate(generators): conditions.append(f'        case {i}: return {cond(g.args[1])};')
        conditions.append('        default: return 0; }')
        generator_count+=len(generators)
    source.extend(['const SceneDefinition scene_definitions[SC_COUNT] = {',*defs,'};',
                   'int scene_due(int scene, int g, int b) {','    switch (scene) {',*conditions,'    default: return 0;','    }','}'])
    header.extend(['    SC_COUNT','};','#endif'])
    return {'src/data_ids.h':'\n'.join(header)+'\n','src/data_generated.inc':'\n'.join(source)+'\n'}, {'text_count':len(totals),'source_bytes':sum(t[-1] for t in totals),'max_text_bytes':max(t[-1] for t in totals),'scene_count':len(names),'generator_count':generator_count}

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    files,stats=export()
    for name,text in files.items():
        path=ROOT/name
        if args.check: assert path.read_text(encoding='utf-8')==text,f'stale export: {name}'
        else: path.write_text(text,encoding='utf-8',newline='\n')
    print(json.dumps(stats))
if __name__=='__main__':main()
