"""Extract event operations in the original same-beat order using a recorder.
The recorder does not run animation callbacks. Runtime random colour choices are
represented as operations, not evaluated into a selected colour.
"""
import json
from pathlib import Path
import sys
import types
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tests'))
from reference import load

def export():
    scope=load(0)
    text_ids={id(v):'TEXT_'+k.upper() for k,v in scope['data_strings'].items()}
    scope['random']=types.SimpleNamespace(choice=lambda _: 'RANDOM_STYLE')
    actions=[]; events=[]
    class Recorder:
        def start_scene(self,scene,at=0): actions.append(('EV_SWAP',scene,-1,at,''))
        def add_scene(self,scene,at=0): actions.append(('EV_LAYER',scene,-1,at,''))
        def remove_scene(self,scene): actions.append(('EV_REMOVE',scene,-1,0,''))
        def set_data(self,*pairs):
            for key,value in zip(pairs[::2],pairs[1::2]):
                if key=='history' and value==[]: actions.append(('EV_HISTORY_RESET','',-1,0,''))
                elif key=='refresh': actions.append(('EV_REFRESH','',-1,int(value),''))
                else: raise ValueError((key,value))
        def set_generator_data(self,scene,gen,*pairs):
            for key,value in zip(pairs[::2],pairs[1::2]):
                if key=='text':
                    if id(value) in text_ids: number=text_ids[id(value)]; string=''
                    elif isinstance(value,str): number=-1;string=value
                    elif value==(('',),('',)): number=-2;string=''
                    else: raise ValueError(value)
                    actions.append(('EV_TEXT',scene,gen,number,string))
                elif key in ('offset','lineno','ocean_glitch'):
                    actions.append(('EV_'+key.upper(),scene,gen,value,''))
                elif key=='ocean_col':
                    actions.append(('EV_RANDOM_COLOUR' if value.startswith('RANDOM_STYLE') else 'EV_COLOUR',scene,gen,0,'' if value.startswith('RANDOM_STYLE') else value))
                else: raise ValueError((key,value))
    recorder=Recorder()
    for beat, group in sorted(scope['controller'].events.items()):
        for index,event in enumerate(group):
            first=len(actions)
            event.do(recorder)
            events.append((beat,index,first,len(actions)-first))
    lines=['/* Generated by tools/export_events.py; order is significant. */','static const EventAction event_actions[] = {']
    for op,scene,gen,num,string in actions:
        lines.append(f'    {{{op}, '+('SC_'+scene.upper() if scene else '-1')+f', {gen}, {num}, '+json.dumps(string)+'},')
    lines.extend(['};','static const TimelineEvent timeline_events[] = {'])
    lines.extend('    {'+', '.join(map(str,event))+'},' for event in events)
    lines.extend(['};',f'enum {{ TIMELINE_EVENTS = {len(events)} }};'])
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    text=export(); path=ROOT/'src/events_generated.inc'
    if '--check' in sys.argv: assert path.read_text(encoding='utf-8')==text
    else: path.write_text(text,encoding='utf-8',newline='\n')
    print('85 ordered events exported; runtime random colour retained')
