"""Build a namespaced, C99 single-header distribution from maintained modules."""
import argparse
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
MODULES='memory random scheduler data credits text scene_init weather60 framebuffer player_fixed ocean60 math_lookup charbuf60 scenes60 text60 animator'.split()
TOKEN=re.compile(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|/\*.*?\*/|//[^\n]*|\b[A-Za-z_]\w*\b', re.S)

def rename(text,names):
    def token(m):
        # Member names occupy a separate C namespace (e.g. noise/next_beat).
        if re.search(r'(?:->|\.)\s*$',text[max(0,m.start()-32):m.start()]):
            return m[0]
        return names.get(m[0],m[0])
    return TOKEN.sub(token,text)

def generate():
    seen=set()
    def expand(path):
        if path.suffix=='.h':
            if path in seen:return ''
            seen.add(path)
        text=path.read_text(encoding='utf-8')
        return re.sub(r'^#include "([^"]+)"\s*$',lambda m:expand(path.parent/m[1]),text,flags=re.M)
    api=expand(ROOT/'src/animator.h')
    implementations=[]
    for module in MODULES:
        code=expand(ROOT/'src'/f'{module}.c')
        locals_=set(re.findall(r'^static[^\n;{}]*?\b([A-Za-z_]\w*)\s*(?=\(|\[|=)',code,re.M))
        code=rename(code,{n:f'credits_private_{module}_{n}' for n in locals_})
        implementations.append(f'\n/* Module: {module}.c */\n'+code)
    implementation='\n'.join(implementations)
    # Keep the public credits_animator/time interface, namespace other definitions.
    private_functions=set(re.findall(r'^(?!static\b)\w[^\n;{}]*?\b(\w+)\([^\n;{}]*\)\s*\{',implementation,re.M))
    private_functions={n for n in private_functions if not n.startswith(('credits_animator_','credits_time_','credits_private_'))}
    private_types=set(re.findall(r'}\s*(\w+)\s*;',api+'\n'+implementation))
    private_types.update(re.findall(r'\benum\s+(\w+)\s*{',api+'\n'+implementation))
    private_types={n for n in private_types if n[0].isupper() and not n.startswith('CreditsAnimator') and n!='CreditsFrameView'}
    private_types.add('FixedTime')
    private_types.add('WeatherNumber')
    names={n:'credits_private_'+n for n in private_functions|private_types|{'scene_definitions'}}
    combined=api+'\n'+implementation
    macros=set(re.findall(r'^#define\s+(\w+)',combined,re.M))
    names.update({n:'CREDITS_PRIVATE_'+n for n in macros if not n.startswith('CREDITS_')})
    api=rename(api,names);implementation=rename(implementation,names)
    return ('/* Generated by tools/export_animator_header.py. C99. Do not edit.\n'
            '   Define CREDITS_ANIMATOR_IMPLEMENTATION in exactly one .c file.\n'
            '   No explicit heap calls. Static instance; do not copy after init. See docs/ANIMATOR_API.md. */\n'
            '#ifndef CREDITS_ANIMATOR_SINGLE_H\n#define CREDITS_ANIMATOR_SINGLE_H\n'
            '#ifndef CREDITS_DIRECT60\n#define CREDITS_DIRECT60 1\n#endif\n'+api+
            '\n#endif /* declarations */\n'
            '#if defined(CREDITS_ANIMATOR_IMPLEMENTATION) && !defined(CREDITS_ANIMATOR_IMPLEMENTED)\n'
            '#define CREDITS_ANIMATOR_IMPLEMENTED\n'+implementation+'\n#endif\n')

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    target=ROOT/'include/credits_animator.h';text=generate()
    if a.check:assert target.read_text(encoding='utf-8')==text,'single header is stale'
    else:target.parent.mkdir(exist_ok=True);target.write_text(text,encoding='utf-8')
